from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.units import inch
import os


def generate_resume_pdf(
    filename,
    resume_text,
    score,
    output_folder="generated_resumes"
):

    # PDF should only be generated if score is 85 or above
    if score < 85:
        return None

    os.makedirs(output_folder, exist_ok=True)

    # Create PDF filename
    pdf_name = os.path.splitext(filename)[0] + "_optimized.pdf"
    pdf_path = os.path.join(output_folder, pdf_name)

    # Create PDF document
    document = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        alignment=TA_CENTER,
        spaceAfter=15
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["BodyText"],
        fontSize=10,
        leading=15,
        spaceAfter=6
    )

    story = []

    # Title
    story.append(
        Paragraph(
            "AI OPTIMIZED RESUME",
            title_style
        )
    )

    story.append(
        Paragraph(
            f"Resume Match Score: {score}%",
            normal_style
        )
    )

    story.append(Spacer(1, 10))

    # Resume content
    story.append(
        Paragraph(
            "Resume Details",
            heading_style
        )
    )

    # Clean resume text
    clean_text = resume_text.replace("&", "&amp;")
    clean_text = clean_text.replace("<", "&lt;")
    clean_text = clean_text.replace(">", "&gt;")

    # Split resume into lines
    lines = clean_text.split("\n")

    for line in lines:

        line = line.strip()

        if line:

            story.append(
                Paragraph(
                    line,
                    normal_style
                )
            )

    story.append(Spacer(1, 15))

    # Score table
    score_data = [
        ["Resume Match Score", f"{score}%"],
        ["PDF Generation Status", "Eligible"],
        ["Minimum Required Score", "85%"]
    ]

    score_table = Table(
        score_data,
        colWidths=[3 * inch, 2 * inch]
    )

    score_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(score_table)

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by AI Resume & Job Application Agent",
            normal_style
        )
    )

    # Build PDF
    document.build(story)

    return pdf_path
