create table if not exists resumes (
    id bigint generated by default as identity primary key,
    file_name text,
    file_url text,
    parsed_text text,
    skills jsonb,
    created_at timestamptz default now()
);

create table if not exists jobs (
    id bigint generated by default as identity primary key,
    job_title text,
    company text,
    description text,
    job_url text,
    source text,
    posted_at timestamptz,
    applicant_count integer,
    required_skills jsonb,
    created_at timestamptz default now()
);

create table if not exists job_matches (
    id bigint generated by default as identity primary key,
    resume_id bigint references resumes(id),
    job_id bigint references jobs(id),
    match_score numeric,
    skills_score numeric,
    missing_skills jsonb,
    drawbacks jsonb,
    recommendations jsonb,
    created_at timestamptz default now()
);

create table if not exists resources (
    id bigint generated by default as identity primary key,
    skill text,
    title text,
    url text,
    resource_type text,
    difficulty text,
    created_at timestamptz default now()
);
